spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotelchaindb
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: password
# App Properties
hotelchainproject:
  app:
    jwtSecret: supersecret
    jwtExpirationMs: 86400000