spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotelchaindb
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
      generate-ddl: true
      show-sql: true
# App Properties
hotelchainproject:
  app:
    jwtSecret: supersecret
    jwtExpirationMs: 86400000